version: '3'
services:
  #  frontend:
  #    container_name: "frontend"
  #    image: krismt/alpine-node
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - './frontend:/app'
  #    depends_on:
  #      - backend
  #    networks:
  #      - webnet
  broker:
    container_name: "broker"
    image: toke/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - webnet
  
  backend:
    container_name: "backend"
    image: krismt/alpine-node
    ports:
      - 3000:3000
    volumes:
      - './mysite:/app'
    depends_on:
      - mongo
    networks:
      - webnet
    links:
      - broker:broker

  monitor:
    container_name: "monitor"
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - webnet

  mongo:
    container_name: "mongo"
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - './data/db:/data/db'
      - './import:/import'
    ports:
      - 27017:27017
    networks:
      - webnet

  #redis:
  #  container_name: "redis"
  #  image: redis:alpine
  #  ports:
  #    - 6379:6379
  #  networks:
  #    - webnet

networks:
    webnet:
